/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author instalador
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        Mensaje.setVisible(false);
        buttonGroup1.add(Option1);
        buttonGroup1.add(Option2);
        buttonGroup1.add(Option3);

        buttonGroup2.add(Option4);
        buttonGroup2.add(Option5);
        buttonGroup2.add(Option6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Option1 = new javax.swing.JRadioButton();
        Option2 = new javax.swing.JRadioButton();
        Option3 = new javax.swing.JRadioButton();
        Check1 = new javax.swing.JCheckBox();
        Check2 = new javax.swing.JCheckBox();
        Check3 = new javax.swing.JCheckBox();
        texto1 = new javax.swing.JTextField();
        Check4 = new javax.swing.JCheckBox();
        Option4 = new javax.swing.JRadioButton();
        Option5 = new javax.swing.JRadioButton();
        Option6 = new javax.swing.JRadioButton();
        Check5 = new javax.swing.JCheckBox();
        Check6 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        texto2 = new javax.swing.JTextField();
        Spin2 = new javax.swing.JSpinner();
        lista1 = new javax.swing.JComboBox<>();
        lista2 = new javax.swing.JComboBox<>();
        Spin1 = new javax.swing.JSpinner();
        Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Option1.setText("Opcion1");
        Option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option1ActionPerformed(evt);
            }
        });

        Option2.setText("Opcion2");
        Option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option2ActionPerformed(evt);
            }
        });

        Option3.setText("Opcion3");
        Option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option3ActionPerformed(evt);
            }
        });

        Check1.setText("CheckBox1");
        Check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check1ActionPerformed(evt);
            }
        });

        Check2.setText("CheckBox2");
        Check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check2ActionPerformed(evt);
            }
        });

        Check3.setText("CheckBox3");
        Check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check3ActionPerformed(evt);
            }
        });

        texto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texto1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texto1KeyReleased(evt);
            }
        });

        Check4.setText("CheckBox1");
        Check4.setEnabled(false);

        Option4.setText("Opcion1");
        Option4.setEnabled(false);

        Option5.setText("Opcion2");
        Option5.setEnabled(false);

        Option6.setText("Opcion3");
        Option6.setEnabled(false);

        Check5.setText("CheckBox2");
        Check5.setEnabled(false);

        Check6.setText("CheckBox3");
        Check6.setEnabled(false);

        lista1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista1ActionPerformed(evt);
            }
        });

        lista2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Spin1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spin1StateChanged(evt);
            }
        });

        Mensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/150pxsvg.png"))); // NOI18N
        Mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Option1)
                            .addComponent(Option2)
                            .addComponent(Option3))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check1)
                            .addComponent(Check2)
                            .addComponent(Check3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Spin1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lista1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Option4)
                                    .addComponent(Option5)
                                    .addComponent(Option6))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Check4)
                                    .addComponent(Check5)
                                    .addComponent(Check6))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lista2, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE)
                                    .addComponent(texto2)
                                    .addComponent(Spin2)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Option1)
                            .addComponent(Check1)
                            .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Option2)
                            .addComponent(Check2)
                            .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Option3)
                            .addComponent(Check3)
                            .addComponent(Spin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Check4)
                            .addComponent(Option4)
                            .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Option5)
                            .addComponent(Check5)
                            .addComponent(lista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Option6)
                            .addComponent(Check6)
                            .addComponent(Spin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option2ActionPerformed
        // TODO add your handling code here:
        if (Option2.isSelected()) {
            this.Option5.setSelected(true);
        } else {
            this.Option5.setSelected(false);
        }

    }//GEN-LAST:event_Option2ActionPerformed

    private void Option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option3ActionPerformed
        // TODO add your handling code here:
        if (Option3.isSelected()) {
            this.Option6.setSelected(true);
        } else {
            this.Option6.setSelected(false);
        }

    }//GEN-LAST:event_Option3ActionPerformed

    private void Check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check1ActionPerformed
        // TODO add your handling code here:

        if (Check1.isSelected()) {
            this.Check4.setSelected(true);
        }

        if (!Check1.isSelected()) {
            this.Check4.setSelected(false);
        }

    }//GEN-LAST:event_Check1ActionPerformed

    private void Check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check2ActionPerformed
        // TODO add your handling code here:
        if (Check2.isSelected()) {
            this.Check5.setSelected(true);
        } else {
            this.Check5.setSelected(false);
        }

    }//GEN-LAST:event_Check2ActionPerformed

    private void Check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check3ActionPerformed
        // TODO add your handling code here:
        if (Check3.isSelected()) {
            this.Check6.setSelected(true);
        } else {
            this.Check6.setSelected(false);
        }

    }//GEN-LAST:event_Check3ActionPerformed

    private void Option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option1ActionPerformed
        // TODO add your handling code here:
        if (Option1.isSelected()) {
            this.Option4.setSelected(true);
        } else {
            this.Option4.setSelected(false);
        }
    }//GEN-LAST:event_Option1ActionPerformed

    private void lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista1ActionPerformed
        // TODO add your handling code here:
        lista2.setSelectedItem(lista1.getSelectedItem());
    }//GEN-LAST:event_lista1ActionPerformed

    private void Spin1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spin1StateChanged
        // TODO add your handling code here:
        Spin2.setValue(Spin1.getValue());
    }//GEN-LAST:event_Spin1StateChanged

    private void texto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_texto1KeyPressed

    private void texto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto1KeyReleased
        String cadena = texto1.getText();

        boolean nom = false;
        boolean pun = false;
        boolean espacio = false;

        nom = (cadena.contains("@"));
        if (nom) {
            nom = true;
        }
        pun = (cadena.contains(".com"));
        if (pun) {
            pun = true;
        }
        espacio = (cadena.contains(" "));

        if (espacio) {
            espacio = true;
        }
        if (nom && pun && !espacio) {
            texto2.setText(cadena);
            Mensaje.setVisible(true);
        } else {
            Mensaje.setText("");
        }

    }//GEN-LAST:event_texto1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check4;
    private javax.swing.JCheckBox Check5;
    private javax.swing.JCheckBox Check6;
    public static javax.swing.JLabel Mensaje;
    private javax.swing.JRadioButton Option1;
    private javax.swing.JRadioButton Option2;
    private javax.swing.JRadioButton Option3;
    private javax.swing.JRadioButton Option4;
    private javax.swing.JRadioButton Option5;
    private javax.swing.JRadioButton Option6;
    private javax.swing.JSpinner Spin1;
    private javax.swing.JSpinner Spin2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> lista1;
    private javax.swing.JComboBox<String> lista2;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    // End of variables declaration//GEN-END:variables
}
